name: TestPlugin
description: A plugin to test all functionality of PabloBot Rewritten
version: 1.2
apiVersion: 1.2
main: me.Logicism.PabloBotRewrittenTestPlugin.TestPlugin
author: Logicism
website: TestWebsite