name: TestPlugin
description: A plugin to test all functionality of PabloBot Rewritten
version: 1.3
apiVersion: 1.4
main: me.Logicism.PabloBotRewrittenTestPlugin.TestPlugin
author: Logicism
website: TestWebsite