name: TestPlugin
description: A plugin to test all functionality of Pablo!
version: 1.4
apiVersion: 1.6
main: me.Logicism.PabloBotRewrittenTestPlugin.TestPlugin
author: Logicism
website: https://logicism.tv/