name: TestPlugin
description: A plugin to test all functionality of Pablo!
version: 1.7
apiVersion: 1.9
main: me.Logicism.PabloBotRewrittenTestPlugin.TestPlugin
author: Logicism
website: https://logicism.tv/