name: TestPlugin
description: A plugin to test all functionality of PabloBot Rewritten
version: 1.4
apiVersion: 1.5
main: me.Logicism.PabloBotRewrittenTestPlugin.TestPlugin
author: Logicism
website: TestWebsite